name: aaronsturgis
favicon: null
layout_spectrum: 0.88263
typography_spectrum: 0.77001
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f8b94'
    - '#92a097'
    - '#216162'
    - '#0c3532'
    - '#0a150e'
  brandStrength: 0.75
  lightness: 0.44996154634281993
  saturation: 0.1431548586115241
  rhythmicContrast: 0.7720306243281811
purpose: []
