name: aaronsturgis
favicon: null
layout_spectrum: 0.38936
typography_spectrum: 0.45013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1c24'
    - '#e5d8d2'
    - '#3c4d5e'
    - '#d4ab99'
    - '#879ead'
  brandStrength: 0.375
  lightness: 0.3125
  saturation: 0.1431548586115241
  rhythmicContrast: 0.25
purpose: []
